@baseurl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpdmFuIiwicm9sZSI6InVzZXIiLCJleHAiOjE3Njg2NjIwNjl9.ecwBwQXgmUkazZCo1LCumwvTMI44b5jHTORugpJh7nM
@advertisement_id = 1b707cff-dcf0-4f02-b73c-965233d9ecc6

### Регистрация пользователя
POST {{baseurl}}/user
Content-Type: application/json

{
  "username": "ivan",
  "role": "user",
  "password": "secret123"
}

### Регистрация пользователя
POST {{baseurl}}/user
Content-Type: application/json

{
  "username": "Ilya",
  "role": "user",
  "password": "secret124"
}

### 2. Вход (получение токена)
POST {{baseurl}}/login
Content-Type: application/json

{
  "username": "ivan",
  "password": "secret123"
}


###

### 3. Получить объявление по ID (без токена)
GET {{baseurl}}/advertisement/{{advertisement_id}}

###

### 4. Создать объявление (с токеном)
POST {{baseurl}}/advertisement
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Продам ноутбук",
  "description": "Рабочий ноутбук, 8 ГБ ОЗУ",
  "price": 25000
}

###

### 5. Обновить объявление (только своё)
PATCH {{baseurl}}/advertisement/{{advertisement_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 23000
}

###

### 6. Удалить объявление (только своё)
DELETE {{baseurl}}/advertisement/{{advertisement_id}}
Authorization: Bearer {{token}}

###

### 7. Поиск объявлений (без токена)
GET {{baseurl}}/advertisement?title=ноутбук&min_price=20000&max_price=30000

###

### 8. Получить пользователя по ID (без токена)
GET {{baseurl}}/user/{{user_id}}

###

### 9. Обновить свои данные (с токеном)
PATCH {{baseurl}}/user/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "ivanov"
}

###

### 10. Удалить себя (с токеном)
DELETE {{baseurl}}/user/{{user_id}}
Authorization: Bearer {{token}}